openapi: 3.0.0
info:
  title: Bulletin Board Service
  description: "This is the API definition for the Bulletin Board Service."
  version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: User
    description: Create and update user


paths:

  /users:
    post:
      tags:
        - User
      summary: Create a new user(CreateUserLambda)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                userId:
                  type: string
      responses:
        "200":
          description: A pantry object
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  userId:
                    type: string
